/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("zux35_trainer1_c_soListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onThezux35_trainer1_c_soListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onThezux35_trainer1_c_soListGenerated.onFilterBar().iCheckFilterField({ property: "Customer" });
            Then.onThezux35_trainer1_c_soListGenerated.onFilterBar().iCheckFilterField({ property: "SalesOrderOverallStatus" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onThezux35_trainer1_c_soListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onThezux35_trainer1_c_soListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onThezux35_trainer1_c_soListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onThezux35_trainer1_c_soListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onThezux35_trainer1_c_soListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onThezux35_trainer1_c_soListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"Customer":{"header":"Kunde"},"SalesOrder":{"header":"Kundenauftr.-ID"},"CompanyName":{"header":"Firma"},"GrossAmountInTransacCurrency":{"header":"Bruttobetrag"},"NetAmountInTransactionCurrency":{"header":"Nettobetr."},"TaxAmountInTransactionCurrency":{"header":"Steuerbetr"},"SalesOrderLifeCycleStatus":{"header":"Lebenszyklusstatus"},"SalesOrderOverallStatus":{"header":"Gesamtstatus"},"TransactionCurrency":{"header":"Währungscode"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onThezux35_trainer1_c_soListGenerated.onFilterBar().iExecuteSearch();
            Then.onThezux35_trainer1_c_soListGenerated.onTable(defaultTableId).iCheckRows();
            When.onThezux35_trainer1_c_soListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onThezux35_trainer1_c_soObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});