/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("zux35_trainer1_c_soObjectPageObjectPage journey");

        opaTest("Navigate to zux35_trainer1_c_soObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThezux35_trainer1_c_soListGenerated.onFilterBar().iExecuteSearch();
            Then.onThezux35_trainer1_c_soListGenerated.onTable().iCheckRows();
            When.onThezux35_trainer1_c_soListGenerated.onTable().iPressRow(0);

            Then.onThezux35_trainer1_c_soObjectPageGenerated.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "FieldGroup::Amount" });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Amount",
                field: "GrossAmountInTransacCurrency",
                targetAnnotation: ""
            });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Amount",
                field: "NetAmountInTransactionCurrency",
                targetAnnotation: ""
            });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Amount",
                field: "TaxAmountInTransactionCurrency",
                targetAnnotation: ""
            });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "FieldGroup::Status" });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Status",
                field: "SalesOrderLifeCycleStatus",
                targetAnnotation: ""
            });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Status",
                field: "SalesOrderOverallStatus",
                targetAnnotation: ""
            });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Status",
                field: "SalesOrderBillingStatus",
                targetAnnotation: ""
            });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "Status",
                field: "SalesOrderDeliveryStatus",
                targetAnnotation: ""
            });
        });

        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onThezux35_trainer1_c_soObjectPageGenerated.iCheckNumberOfSections(3);
        });

        opaTest("Check the SECTION1 section of the Object Page", function (_Given, When, Then) {
            When.onThezux35_trainer1_c_soObjectPageGenerated.iPressSectionIconTabFilterButton("SECTION1");
            Then.onThezux35_trainer1_c_soObjectPageGenerated.iCheckSection({ section: "SECTION1" });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onForm({ section: "SECTION1" }).iCheckField({ property: "SalesOrder" });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onForm({ section: "SECTION1" }).iCheckField({ property: "Customer" });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onForm({ section: "SECTION1" }).iCheckField({ property: "CompanyName" });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onForm({ section: "SECTION1" }).iCheckField({ property: "CreatedByUser" });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onForm({ section: "SECTION1" }).iCheckField({ property: "CreationDateTime" });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onForm({ section: "SECTION1" }).iCheckField({ property: "LastChangedByUser" });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onForm({ section: "SECTION1" }).iCheckField({ property: "LastChangedDateTime" });
        });

        opaTest("Check the SECTION2 section of the Object Page", function (_Given, When, Then) {
            When.onThezux35_trainer1_c_soObjectPageGenerated.iPressSectionIconTabFilterButton("SECTION2");
            Then.onThezux35_trainer1_c_soObjectPageGenerated.iCheckSection({ section: "SECTION2" });
            Then.onThezux35_trainer1_c_soObjectPageGenerated.onTable({ property: "_Item" }).iCheckColumns(undefined, {"SalesOrderItem":{"header":"Zeile der Position"},"Product":{"header":"Produkt-ID"},"ProductSize":{"header":"ProductSize"},"DataFieldForAnnotation::DataPoint::Weight2":{"header":"Visual: Progress"},"DataFieldForAnnotation::DataPoint::Rating":{"header":"Visual: Rating"},"TransactionCurrency":{"header":"Währungscode"},"GrossAmountInTransacCurrency":{"header":"Bruttobetrag"},"NetAmountInTransactionCurrency":{"header":"Nettobetr."},"TaxAmountInTransactionCurrency":{"header":"Steuerbetr"},"ProductAvailabilityStatus":{"header":"ATP-Status"},"OpportunityItem":{"header":"Zeile der Position"},"Quantity":{"header":"Menge"},"QuantityUnit":{"header":"Maßeinheit"}});
        });

        opaTest("Check the SECTION3 section of the Object Page", function (_Given, When, Then) {
            When.onThezux35_trainer1_c_soObjectPageGenerated.iPressSectionIconTabFilterButton("SECTION3");
            Then.onThezux35_trainer1_c_soObjectPageGenerated.iCheckSection({ section: "SECTION3" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});